Update wme-sitebuilder data structure
moderntribe/wme pull request #177
Opened 2023-01-09 15:39 UTC by chumpgrub

- Changes `CARDS` constant to draw data from backend and not JSON
- Updates backend data structure returns for updated frontend requirements

2023-01-09 16:03 UTC, aykanburcak approved these changes

2023-01-09 16:47 UTC, bswatson requested changes

2023-01-09 16:47 UTC, bswatson commented on packages/sitebuilder/src/constants/index.ts
> +//export const CARDS: SetupCardInterface[] = cardsJson;
If this code is not intended to come back, remove the line completely instead of commenting it out.

2023-01-09 16:47 UTC, bswatson commented on plugins/wme-sitebuilder/wme-sitebuilder/Cards/GoLive.php
> +			'intro'     => __( 'Vivamus sagittis lacus vel augue laoreet.', 'wme-sitebuilder' ),
Replace the placeholder text with something else.

2023-01-09 16:47 UTC, bswatson commented on plugins/wme-sitebuilder/wme-sitebuilder/Cards/LookAndFeel.php
> +			'intro'     => __( 'Curabitur blandit tempus porttitor.', 'wme-sitebuilder' ),
Replace placeholder text with real text before merging to main/v2 branch.

2023-01-09 16:47 UTC, bswatson commented on plugins/wme-sitebuilder/wme-sitebuilder/Cards/LookAndFeel.php
> +				'intro'      => __( 'Lorem ipsum dolor sit.', 'wme-sitebuilder' ),
Replace placeholder text with real text before merging to main/v2 branch.

2023-01-09 16:50 UTC, lukefrogger approved these changes
Looks good!

2023-01-10 15:01 UTC, lukefrogger commented on packages/sitebuilder/src/constants/index.ts
> +export const CARDS: SetupCardInterface[] = SITEBUILDER.cards || [];
You probably want to remove the `cards.json` import and the entire file unless you're holding onto it for some reason.

2023-01-10 19:08 UTC, bswatson approved these changes

2023-01-10 19:54 UTC, merged