chore: Shipping card footer links
moderntribe/wme pull request #245
Opened 2023-04-27 11:30 UTC by aykanburcak

2023-04-27 14:16 UTC, chumpgrub approved these changes
👍

2023-04-27 15:19 UTC, bswatson requested changes

2023-04-27 15:19 UTC, bswatson commented on plugins/wme-sitebuilder/wme-sitebuilder/Plugins/Shipping.php
> +				'href' => 'https://wordpress.org/plugins/elex-usps-shipping-method/#:~:text=ELEX%20USPS%20Shipping%20Method%20for,shipping%20address%20and%20cart%20content.',
I don't think we would want the text to be highlighted in Chrome based on `#:~:text=ELEX%20USPS%20Shipping%20Method%20for,shipping%20address%20and%20cart%20content.`

2023-04-27 15:19 UTC, bswatson commented on plugins/wme-sitebuilder/wme-sitebuilder/Plugins/Shipping.php
> +				'href' => 'https://woocommerce.com/document/flat-rate-shipping/?quid=82cd3e1acfe149c4e92b227edc8761a1',
Recommend removing the `quid` var here.

2023-04-28 15:47 UTC, bswatson approved these changes

2023-05-01 15:25 UTC, merged